import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  awsSidebar: [
    {
      type: 'category',
      label: 'Networking',
      link: { type: 'doc', id: 'aws/networking/networking-intro' },
      collapsible: true,
      collapsed: true,
      items: [
          {
            type: 'category',
            label: 'VPC',
            link: { type: 'doc', id: 'aws/networking/vpc/vpc-intro' },
            items: [
              'aws/networking/vpc/subnets',
              'aws/networking/vpc/routing',
              'aws/networking/vpc/igw',
              'aws/networking/vpc/natgateway',
              'aws/networking/vpc/privatevspublic',
              'aws/networking/vpc/dns',
              'aws/networking/vpc/elasticip',
            ],
          },
          {
            type: 'category',
            label: 'Firewalls',
            link: { type: 'doc', id: 'aws/networking/firewalls/firewalls-intro' },
            items: [
              'aws/networking/firewalls/nacls',
              'aws/networking/firewalls/security-groups',
            ],
          },
          {
            type: 'category',
            label: 'Load Balancers',
            link: { type: 'doc', id: 'aws/networking/load-balancers/load-balancers-intro' },
            items: [
              'aws/networking/load-balancers/classic-load-balancer',
              'aws/networking/load-balancers/application-load-balancer',
              'aws/networking/load-balancers/network-load-balancer',
              'aws/networking/load-balancers/load-balancer-comparison',
              'aws/networking/load-balancers/cross-zone-load-balancing',
              'aws/networking/load-balancers/other-elb-considerations',
            ],
          }
        ],
  },
  ],
  kubernetesSidebar: [{type: 'autogenerated', dirName: 'kubernetes'}],
  terraformSidebar: [{type: 'autogenerated', dirName: 'terraform'}],
};

export default sidebars;
