import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  kubernetesSidebar: [{type: 'autogenerated', dirName: 'kubernetes'}],
  awsSidebar: [
    {
      type: 'category',
      label: 'Networking',
      items: [
          {
            type: 'category',
            label: 'VPC',
            link: { type: 'doc', id: 'aws/networking/vpc/vpc-intro' },
            items: [
              'aws/networking/vpc/subnets',
              'aws/networking/vpc/routing',
              'aws/networking/vpc/igw',
            ],
          },
          {
            type: 'category',
            label: 'Firewalls',
            link: { type: 'doc', id: 'aws/networking/firewalls' },
            items: [
              'aws/networking/security-groups',
              'aws/networking/nacls',
            ],
          },
          'aws/networking/load-balancers',
        ],
  },
  ],
  terraformSidebar: [{type: 'autogenerated', dirName: 'terraform'}],
};

export default sidebars;
